name: Edinburgh Holiday Home
favicon: null
layout_spectrum: 0.3139209267683327
typography_spectrum: 0.281951439101249
title: Edinburgh City Centre flat for holiday let
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4d4ba'
    - '#9e0003'
    - '#8c7d6a'
    - '#5b4c39'
    - '#e97491'
  brandStrength: 0.9158629239536822
  lightness: 0.3650572698097676
  saturation: 0.837204544339329
  rhythmicContrast: 0.33010457921773195
purpose: []
